DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS product;

CREATE TABLE product (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     name VARCHAR(100) NOT NULL,
     price DECIMAL(12, 2) NOT NULL,
     stock INT NOT NULL DEFAULT 0,
     status VARCHAR(20) NOT NULL,
     created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

     PRIMARY KEY (id),

     CONSTRAINT chk_product_name
         CHECK (CHAR_LENGTH(TRIM(name)) > 0),

     CONSTRAINT chk_product_stock
         CHECK (stock >= 0),

     CONSTRAINT chk_product_price
         CHECK (price >= 0.01),

     CONSTRAINT chk_product_status
         CHECK (
             status IN (
                        'ON_SALE',
                        'OUT_OF_STOCK',
                        'OFF_SHELF'
                 )
             )
);

CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    total_amount DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    CONSTRAINT chk_order_quantity
        CHECK (quantity >= 1),

    CONSTRAINT chk_order_total
        CHECK (total_amount >= 0),

    CONSTRAINT chk_order_status
        CHECK (status IN ('CREATED', 'PAID', 'CANCELLED')),

    CONSTRAINT fk_order_product
        FOREIGN KEY (product_id) REFERENCES product (id)
);
