DROP TABLE IF EXISTS product;

CREATE TABLE product (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY,
     name VARCHAR(100) NOT NULL,
     price DECIMAL(12, 2) NOT NULL,
     status VARCHAR(20) NOT NULL,
     created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

     PRIMARY KEY (id),

     CONSTRAINT chk_product_name
         CHECK (CHAR_LENGTH(TRIM(name)) > 0),

     CONSTRAINT chk_product_price
         CHECK (price >= 0.01),

     CONSTRAINT chk_product_status
         CHECK (
             status IN (
                        'ON_SALE',
                        'OUT_OF_STOCK',
                        'OFF_SHELF'
                 )
             )
);